/**
 * short-pia.js — Short-form PIA question definitions.
 *
 * Based on the OAIC Short-form Privacy Impact Assessment template.
 * Sections map to the five main areas of a short-form PIA.
 * Customise questions by editing the STEPS array below.
 */

export const ASSESSMENT_TYPE = 'short';

export const STEPS = [
  /* ── Section 1: Project overview ──────────────────────────── */
  {
    id:    'project-overview',
    title: 'Project overview',
    desc:  'Provide basic information about the project or activity being assessed.',
    fields: [
      {
        id:       'project_name',
        type:     'text',
        label:    'Project / activity name',
        required: true,
        placeholder: 'e.g. Staff Performance Management System',
      },
      {
        id:       'project_purpose',
        type:     'textarea',
        label:    'Purpose of the project',
        hint:     'What problem does this project solve? What are its goals?',
        required: true,
        placeholder: 'Describe the purpose and intended outcomes...',
      },
      {
        id:       'project_description',
        type:     'textarea',
        label:    'Description of the project',
        hint:     'Summarise the key activities, systems, or processes involved.',
        required: true,
        placeholder: 'Provide a brief overview of how the project will work...',
      },
      {
        id:       'project_stage',
        type:     'select',
        label:    'Project stage',
        hint:     'OAIC guidance recommends PIAs are conducted at the planning or design stage, before significant decisions are locked in.',
        required: false,
        options: [
          { value: '',         label: '— Select —' },
          { value: 'Planning', label: 'Planning' },
          { value: 'Design',   label: 'Design' },
          { value: 'Build',    label: 'Build' },
          { value: 'In use',   label: 'In use / operational' },
          { value: 'Review',   label: 'Review / post-implementation' },
        ],
      },
      {
        id:       'project_owner',
        type:     'text',
        label:    'Project owner',
        required: true,
        placeholder: 'e.g. Jane Smith, Head of People & Culture',
      },
      {
        id:       'privacy_contact',
        type:     'text',
        label:    'Privacy contact / privacy officer',
        required: false,
        placeholder: 'e.g. John Lee, Privacy Officer',
      },
      {
        id:       'start_date',
        type:     'date',
        label:    'Proposed project start date',
        required: false,
      },
      {
        id:       'assessment_date',
        type:     'date',
        label:    'Date of this assessment',
        required: true,
      },
      {
        id:       'threshold_ref',
        type:     'text',
        label:    'Threshold assessment reference (if applicable)',
        hint:     'Reference any threshold assessment already completed for this project.',
        required: false,
        placeholder: 'e.g. TA-2026-001 or leave blank',
      },
      {
        id:       'legislative_context',
        type:     'textarea',
        label:    'Applicable legislation or policy',
        hint:     'List any legislation, regulations, or organisational policies relevant to privacy in this project.',
        required: false,
        placeholder: 'e.g. Privacy Act 1988 (Cth), Privacy and Other Legislation Amendment Act 2024 (Cth), Health Records Act 2001 (Vic)...',
      },
    ],
  },

  /* ── Section 2: Personal information involved ──────────────── */
  {
    id:    'personal-information',
    title: 'Personal information involved',
    desc:  'Describe the personal information the project collects, holds, uses, or discloses.',
    fields: [
      {
        id:       'info_types',
        type:     'checkbox-other',
        label:    'What personal information is collected or used?',
        hint:     'Select all categories that apply. Use "Other" to add anything not listed.',
        required: true,
        options: [
          { value: 'contact',      label: 'Name and contact details (email, phone, postal address)' },
          { value: 'dob',          label: 'Date of birth or age' },
          { value: 'identity_doc', label: 'Identity documents (passport, driver's licence, proof of age)' },
          { value: 'financial',    label: 'Financial information (bank account, credit card, income, tax details)' },
          { value: 'health',       label: 'Health or medical information (diagnoses, medications, clinical records)' },
          { value: 'employment',   label: 'Employment information (job title, performance records, salary)' },
          { value: 'education',    label: 'Education or qualifications' },
          { value: 'location',     label: 'Location or tracking data (GPS, movements, proximity)' },
          { value: 'online_id',    label: 'Online identifiers (IP address, cookies, device ID, usernames)' },
          { value: 'images',       label: 'Images or recordings (photographs, CCTV footage, audio)' },
          { value: 'gov_id',       label: 'Government identifiers (Tax File Number, Medicare number)' },
          { value: 'racial',       label: 'Racial or ethnic origin' },
          { value: 'biometric',    label: 'Biometric information (fingerprints, facial geometry, voice prints)' },
          { value: 'genetic',      label: 'Genetic information (DNA, genomic data)' },
          { value: 'children',     label: 'Children\'s or minors\' information (under 18)' },
        ],
      },
      {
        id:       'info_subjects',
        type:     'checkbox-other',
        label:    'Whose personal information is involved?',
        hint:     'Select all groups whose information is collected or used.',
        required: true,
        options: [
          { value: 'customers',    label: 'Customers or clients' },
          { value: 'employees',    label: 'Current employees or staff' },
          { value: 'ex_employees', label: 'Former employees' },
          { value: 'applicants',   label: 'Job applicants or candidates' },
          { value: 'contractors',  label: 'Contractors or suppliers' },
          { value: 'members',      label: 'Members or subscribers' },
          { value: 'public',       label: 'Members of the general public' },
          { value: 'students',     label: 'Students or learners' },
          { value: 'minors',       label: 'Children or minors (under 18)' },
        ],
      },
      {
        id:       'collection_method',
        type:     'checkbox-other',
        label:    'How is personal information collected?',
        hint:     'Select all collection methods that apply.',
        required: true,
        options: [
          { value: 'online_form',  label: 'Online form or web portal' },
          { value: 'mobile_app',   label: 'Mobile app' },
          { value: 'paper_form',   label: 'Paper form or hard copy' },
          { value: 'in_person',    label: 'In-person interaction (interview, reception, counter)' },
          { value: 'phone',        label: 'Phone or video call' },
          { value: 'email',        label: 'Email' },
          { value: 'cctv',         label: 'CCTV or surveillance system' },
          { value: 'third_party',  label: 'Third-party data provider or data broker' },
          { value: 'automated',    label: 'Automated collection (API, sensor, cookie, tracking pixel)' },
          { value: 'purchased',    label: 'Purchased or licensed dataset' },
        ],
      },
      {
        id:       'collection_notice',
        type:     'radio',
        label:    'Will individuals be notified about collection of their personal information (Privacy Notice)?',
        required: true,
        options: [
          { value: 'yes',     label: 'Yes — a collection notice will be provided' },
          { value: 'no',      label: 'No — collection notice is not planned' },
          { value: 'partial', label: 'Partial — a notice exists but needs updating' },
          { value: 'unsure',  label: 'Unsure' },
        ],
      },
      {
        id:       'collection_notice_notes',
        type:     'textarea',
        label:    'Notes on collection notice',
        required: false,
        placeholder: 'Describe where and how the notice will be provided, or explain why one is not required...',
      },
      {
        id:       'sensitive_info',
        type:     'radio',
        label:    'Does the project involve sensitive information as defined in the Privacy Act?',
        hint:     'Sensitive information includes health, racial/ethnic origin, religious beliefs, criminal record, biometric and genetic data, sexual orientation, and more.',
        required: true,
        options: [
          { value: 'yes',    label: 'Yes' },
          { value: 'no',     label: 'No' },
          { value: 'unsure', label: 'Unsure' },
        ],
      },
      {
        id:       'sensitive_details',
        type:     'textarea',
        label:    'Describe the sensitive information and the legal basis for collecting it',
        required: false,
        placeholder: 'e.g. Health information collected with employee consent for workplace safety purposes...',
        showIf: { field: 'sensitive_info', values: ['yes', 'unsure'] },
      },
      {
        id:       'children_involved',
        type:     'radio',
        label:    'Does this project involve children or young people under 16, or is it likely to be accessed by them?',
        hint:     'The Privacy and Other Legislation Amendment Act 2024 (Cth) introduces a Children\'s Online Privacy Code. Projects involving children\'s personal information require heightened protections.',
        required: true,
        options: [
          { value: 'yes',    label: 'Yes' },
          { value: 'no',     label: 'No' },
          { value: 'unsure', label: 'Unsure' },
        ],
      },
      {
        id:          'children_details',
        type:        'textarea',
        label:       'Describe how children\'s privacy is protected',
        hint:        'Include age assurance mechanisms, parental or guardian consent arrangements, and any data minimisation steps specific to minors.',
        required:    false,
        placeholder: 'e.g. Age verification is required at sign-up; no behavioural profiling of users under 16; parental consent obtained for health-related data...',
        showIf: { field: 'children_involved', values: ['yes', 'unsure'] },
      },
      {
        id:       'direct_marketing',
        type:     'radio',
        label:    'Does this project involve direct marketing, targeted advertising, or profiling of individuals?',
        hint:     'Individuals have a right to opt out of direct marketing and targeting under the Privacy and Other Legislation Amendment Act 2024 (Cth). This includes behavioural advertising and algorithmic profiling.',
        required: true,
        options: [
          { value: 'yes',    label: 'Yes' },
          { value: 'no',     label: 'No' },
          { value: 'unsure', label: 'Unsure' },
        ],
      },
      {
        id:          'direct_marketing_details',
        type:        'textarea',
        label:       'Describe the opt-out mechanism and how individuals can exercise their right to opt out',
        required:    false,
        placeholder: 'e.g. Unsubscribe link in all marketing emails; preference centre at account settings; opt-out requests honoured within 5 business days...',
        showIf: { field: 'direct_marketing', values: ['yes', 'unsure'] },
      },
      {
        id:       'retention_period',
        type:     'select',
        label:    'Retention period',
        hint:     'How long will personal information be held? Select the closest match.',
        required: false,
        options: [
          { value: '',                   label: '— Select —' },
          { value: 'Under 12 months',    label: 'Under 12 months' },
          { value: '1–3 years',          label: '1–3 years' },
          { value: '3–7 years',          label: '3–7 years' },
          { value: '7 years',            label: '7 years (financial / tax obligation)' },
          { value: 'Until purpose ends', label: 'Until the purpose is fulfilled, then destroy' },
          { value: 'Legislation',        label: 'As specified by legislation or policy' },
          { value: 'Indefinitely',       label: 'Indefinitely (with documented justification)' },
        ],
      },
      {
        id:       'disposal_method',
        type:     'checkbox-other',
        label:    'How will personal information be securely disposed of?',
        hint:     'Select all disposal methods that will be used.',
        required: false,
        options: [
          { value: 'secure_delete',  label: 'Secure digital deletion or overwriting (e.g. NIST SP 800-88)' },
          { value: 'crypto_erase',   label: 'Cryptographic erasure (deletion of encryption keys)' },
          { value: 'hw_destroy',     label: 'Physical destruction of hardware (degaussing, shredding drives)' },
          { value: 'paper_shred',    label: 'Shredding of paper documents' },
          { value: 'anonymise',      label: 'Anonymisation or de-identification' },
          { value: 'archive',        label: 'Archiving to long-term secure storage' },
        ],
      },
    ],
  },

  /* ── Section 3: Information flows ─────────────────────────── */
  {
    id:    'information-flows',
    title: 'Information flows',
    desc:  'Describe how personal information moves within and outside the organisation.',
    fields: [
      {
        id:       'internal_access',
        type:     'checkbox-other',
        label:    'Who within the organisation has access to the personal information?',
        hint:     'Select all roles or teams that will access this information.',
        required: true,
        options: [
          { value: 'exec',       label: 'Senior management or executive team' },
          { value: 'privacy',    label: 'Privacy officer or compliance team' },
          { value: 'hr',         label: 'Human resources team' },
          { value: 'it',         label: 'IT and systems administrators' },
          { value: 'frontline',  label: 'Customer-facing or frontline staff' },
          { value: 'finance',    label: 'Finance and accounts team' },
          { value: 'legal',      label: 'Legal and risk team' },
          { value: 'marketing',  label: 'Marketing and communications team' },
          { value: 'all_staff',  label: 'All staff (with appropriate access controls)' },
        ],
      },
      {
        id:       'storage_location',
        type:     'checkbox-other',
        label:    'Where is personal information stored?',
        hint:     'Select all storage locations or systems used.',
        required: true,
        options: [
          { value: 'cloud_au',     label: 'Cloud platform — Australian data centres' },
          { value: 'cloud_os',     label: 'Cloud platform — overseas data centres' },
          { value: 'on_prem',      label: 'On-premises servers or data centre' },
          { value: 'end_user',     label: 'End-user devices (laptops, phones, tablets)' },
          { value: 'paper',        label: 'Paper or physical files (locked cabinets)' },
          { value: 'third_party',  label: 'Third-party managed service provider' },
          { value: 'removable',    label: 'Removable or portable media (USB drives, external hard drives)' },
        ],
      },
      {
        id:       'security_measures',
        type:     'checkbox-other',
        label:    'What security measures protect the personal information?',
        hint:     'Select all controls that are in place or planned. (APP 11)',
        required: true,
        options: [
          { value: 'encrypt_rest',    label: 'Encryption at rest (e.g. AES-256)' },
          { value: 'encrypt_transit', label: 'Encryption in transit (TLS/SSL)' },
          { value: 'mfa',             label: 'Multi-factor authentication (MFA)' },
          { value: 'rbac',            label: 'Role-based access controls (RBAC)' },
          { value: 'audit_logs',      label: 'Audit logging and monitoring' },
          { value: 'backup',          label: 'Data backup and recovery procedures' },
          { value: 'physical',        label: 'Physical security controls (restricted access, locks, alarms)' },
          { value: 'training',        label: 'Privacy and security training for staff' },
          { value: 'dlp',             label: 'Data Loss Prevention (DLP) tools' },
          { value: 'pen_test',        label: 'Regular penetration testing or security audits' },
          { value: 'patching',        label: 'Vulnerability scanning and patch management' },
        ],
      },
      {
        id:       'ndb_plan',
        type:     'radio',
        label:    'Does the organisation have a Notifiable Data Breach (NDB) response plan covering this project or system?',
        hint:     'The Privacy and Other Legislation Amendment Act 2024 (Cth) strengthens NDB obligations, including more granular notification thresholds and tighter reporting timelines. All covered entities must be able to assess and notify eligible data breaches promptly.',
        required: true,
        options: [
          { value: 'yes',         label: 'Yes — a current NDB response plan is in place' },
          { value: 'no',          label: 'No — one needs to be developed' },
          { value: 'in_progress', label: 'In progress — being developed or updated' },
        ],
      },
      {
        id:       'third_party_disclosure',
        type:     'radio',
        label:    'Is personal information disclosed to any third parties?',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no',  label: 'No' },
        ],
      },
      {
        id:       'third_party_details',
        type:     'checkbox-other',
        label:    'Which types of third parties receive this information?',
        hint:     'Select all that apply, then use "Other" to name specific providers.',
        required: false,
        showIf: { field: 'third_party_disclosure', values: ['yes'] },
        options: [
          { value: 'it_providers',  label: 'IT service providers or cloud hosting providers' },
          { value: 'payment',       label: 'Payment processors (e.g. Stripe, Westpac, Tyro)' },
          { value: 'analytics',     label: 'Analytics or digital marketing platforms' },
          { value: 'hr_platform',   label: 'Recruitment or HR software platforms' },
          { value: 'professional',  label: 'Legal, accounting, or professional advisory firms' },
          { value: 'government',    label: 'Government agencies (as required by law)' },
          { value: 'research',      label: 'Research partners or academic institutions' },
          { value: 'overseas_ent',  label: 'Overseas related entities or subsidiaries' },
        ],
      },
      {
        id:       'overseas_transfer',
        type:     'radio',
        label:    'Is personal information transferred or stored outside Australia?',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no',  label: 'No' },
        ],
      },
      {
        id:       'overseas_details',
        type:     'checkbox-other',
        label:    'Which countries receive or store this personal information?',
        hint:     'APP 8 requires that cross-border disclosures comply with comparable privacy protections. Use "Other" to list additional countries.',
        required: false,
        showIf: { field: 'overseas_transfer', values: ['yes'] },
        options: [
          { value: 'us',  label: 'United States' },
          { value: 'uk',  label: 'United Kingdom' },
          { value: 'eu',  label: 'European Union' },
          { value: 'nz',  label: 'New Zealand' },
          { value: 'in',  label: 'India' },
          { value: 'ph',  label: 'Philippines' },
          { value: 'sg',  label: 'Singapore' },
          { value: 'ca',  label: 'Canada' },
          { value: 'jp',  label: 'Japan' },
        ],
      },
    ],
  },

  /* ── Section 4: Privacy risk register ─────────────────────── */
  {
    id:    'risk-register',
    title: 'Privacy risk register',
    desc:  'Identify and assess privacy risks associated with the project, and document proposed treatments.',
    hint:  'Add at least one risk. Select a risk category — a suggested treatment will be pre-filled for you to edit.',
    fields: [
      {
        id:       'risks',
        type:     'repeating-group',
        label:    'Privacy risks',
        addLabel: '+ Add another risk',
        minItems: 1,
        subfields: [
          {
            id:           'risk_category',
            type:         'select',
            label:        'Risk category',
            required:     true,
            suggestField: 'treatment',
            suggestions:  {
              'unauthorised_access':   'Implement multi-factor authentication (MFA) and role-based access controls (RBAC). Conduct regular user access reviews. Encrypt data at rest and in transit. Monitor access logs for anomalies.',
              'data_breach':           'Develop and test a Data Breach Response Plan aligned to the updated NDB scheme (Privacy and Other Legislation Amendment Act 2024). Establish clear internal triage and escalation procedures. Notify affected individuals and the OAIC promptly if a breach is eligible — the 2024 Act introduces tighter timelines and more granular notification thresholds. Conduct a post-incident review and update controls accordingly.',
              'excessive_collection':  'Apply data minimisation principles — only collect what is reasonably necessary for the stated purpose (APP 3). Review all collection forms and remove unnecessary fields. Document the justification for each data element collected.',
              'poor_data_quality':     'Implement validation checks at collection to ensure accuracy. Provide individuals with access and correction rights (APP 12, APP 13). Schedule regular data quality reviews and cleansing processes.',
              'insecure_storage':      'Encrypt stored data (AES-256 or equivalent). Apply secure configuration baselines to all systems. Conduct regular vulnerability assessments and penetration testing. Implement backup and recovery procedures.',
              'unlawful_use':          'Review all use and disclosure activities against APP 6. Obtain appropriate consent or identify another lawful basis. Update privacy notices to accurately reflect actual data processing. Brief staff on permitted uses.',
              'lack_of_transparency':  'Update the Privacy Policy and collection notices to clearly describe how personal information is handled. Ensure notices are written in plain language and made easily accessible. Conduct a review against APP 1 and APP 5 requirements.',
              'excessive_retention':   'Implement an automated data retention and disposal schedule. Set system triggers for deletion at the end of the retention period. Conduct periodic audits of data holdings against the documented retention policy.',
              'cross_border':          'Review cross-border disclosure arrangements against APP 8. Implement appropriate contractual protections (e.g. Standard Contractual Clauses). Assess whether the destination country has comparable privacy protections. Document the basis for transfer.',
              'identity_fraud':        'Apply strict controls on use of government identifiers (APP 9). Limit collection and use of TFN, Medicare number and similar identifiers to legally authorised purposes only. Implement strong authentication and fraud monitoring.',
              'inadequate_consent':    'Review consent mechanisms to ensure they are freely given, specific, informed, and unambiguous. Provide clear opt-out mechanisms. Document consent records. Ensure consent is refreshed when processing purposes change.',
              'doxxing':               'Implement strict access controls to prevent unauthorised sharing of personal information via public channels. The Privacy and Other Legislation Amendment Act 2024 (Cth) introduces criminal offences for doxxing (malicious public disclosure of personal data). Conduct staff training on acceptable information handling. Monitor public-facing outputs (e.g. generated content, directories) for inadvertent personal information exposure. Establish an incident reporting pathway.',
              'childrens_privacy':     'Comply with the Children\'s Online Privacy Code (Privacy and Other Legislation Amendment Act 2024). Implement age verification or age assurance mechanisms proportionate to risk. Obtain enhanced parental or guardian consent for children under 16. Apply strict data minimisation — collect only what is necessary for the service. Disable behavioural profiling and targeted advertising for users under 16. Document compliance steps and review regularly.',
              'targeting_profiling':   'Establish a clear, accessible opt-out mechanism for direct marketing and targeting, as required under the Privacy and Other Legislation Amendment Act 2024 (Cth). Maintain suppression lists and honour opt-out requests within the required timeframe. Review all profiling and targeting activities to ensure they are disclosed in the Privacy Policy and collection notices. Cease targeted advertising to individuals who have opted out.',
              'privacy_tort':          'The Privacy and Other Legislation Amendment Act 2024 (Cth) introduces a statutory tort for serious invasions of privacy. Minimise the risk of individual legal action by: ensuring a lawful basis for all processing activities; avoiding highly intrusive data uses without clear justification; providing meaningful transparency and control to individuals; and establishing an accessible privacy complaint mechanism that resolves concerns promptly at first contact.',
            },
            options: [
              { value: '',                    label: '— Select a risk category —' },
              { value: 'unauthorised_access',  label: 'Unauthorised access to personal information' },
              { value: 'data_breach',          label: 'Data breach or inadvertent disclosure' },
              { value: 'excessive_collection', label: 'Excessive or unnecessary collection (APP 3)' },
              { value: 'poor_data_quality',    label: 'Inaccurate or out-of-date information (APP 10)' },
              { value: 'insecure_storage',     label: 'Insecure data storage or transmission (APP 11)' },
              { value: 'unlawful_use',         label: 'Unlawful or non-consensual use or disclosure (APP 6)' },
              { value: 'lack_of_transparency', label: 'Lack of transparency or inadequate notice (APP 1, APP 5)' },
              { value: 'excessive_retention',  label: 'Retention of data beyond required period (APP 11)' },
              { value: 'cross_border',         label: 'Cross-border transfer without adequate protection (APP 8)' },
              { value: 'identity_fraud',       label: 'Identity theft, fraud, or misuse of identifiers (APP 9)' },
              { value: 'inadequate_consent',   label: 'Inadequate or invalid consent' },
              { value: 'doxxing',              label: 'Doxxing or malicious public disclosure of personal information' },
              { value: 'childrens_privacy',    label: 'Children\'s privacy or failure to meet age assurance obligations (Children\'s Online Privacy Code)' },
              { value: 'targeting_profiling',  label: 'Unlawful direct marketing, profiling, or failure to honour opt-out requests' },
              { value: 'privacy_tort',         label: 'Exposure to statutory privacy tort (serious invasion of privacy)' },
            ],
          },
          {
            id:          'risk_description',
            type:        'textarea',
            label:       'Risk description',
            hint:        'Describe the specific risk scenario for this project — what could go wrong and how it could affect individuals.',
            required:    true,
            placeholder: 'Describe the specific risk in the context of this project...',
          },
          {
            id:       'likelihood',
            type:     'select',
            label:    'Likelihood',
            required: true,
            options: [
              { value: '',       label: '— Select —' },
              { value: 'High',   label: 'High' },
              { value: 'Medium', label: 'Medium' },
              { value: 'Low',    label: 'Low' },
            ],
          },
          {
            id:       'consequence',
            type:     'select',
            label:    'Consequence',
            required: true,
            options: [
              { value: '',       label: '— Select —' },
              { value: 'High',   label: 'High' },
              { value: 'Medium', label: 'Medium' },
              { value: 'Low',    label: 'Low' },
            ],
          },
          {
            id:       'risk_rating',
            type:     'select',
            label:    'Overall risk rating',
            required: true,
            options: [
              { value: '',           label: '— Select —' },
              { value: 'Critical',   label: 'Critical' },
              { value: 'High',       label: 'High' },
              { value: 'Medium',     label: 'Medium' },
              { value: 'Low',        label: 'Low' },
              { value: 'Negligible', label: 'Negligible' },
            ],
          },
          {
            id:          'treatment',
            type:        'textarea',
            label:       'Proposed treatment / control',
            hint:        'A suggested treatment has been pre-filled based on the risk category. Edit or replace it to reflect your specific context.',
            required:    true,
            placeholder: 'Select a risk category above to receive a suggested treatment, or describe your planned control here...',
          },
          {
            id:       'residual_risk',
            type:     'select',
            label:    'Residual risk (after treatment)',
            required: false,
            options: [
              { value: '',           label: '— Select —' },
              { value: 'High',       label: 'High' },
              { value: 'Medium',     label: 'Medium' },
              { value: 'Low',        label: 'Low' },
              { value: 'Negligible', label: 'Negligible' },
            ],
          },
          {
            id:          'risk_owner',
            type:        'text',
            label:       'Risk owner',
            required:    false,
            placeholder: 'e.g. IT Security Manager',
          },
        ],
      },
    ],
  },

  /* ── Section 5: Recommendations and sign-off ───────────────── */
  {
    id:    'recommendations',
    title: 'Recommendations and sign-off',
    desc:  'Summarise the recommendations arising from this assessment and record sign-off details.',
    fields: [
      {
        id:       'recommendations_text',
        type:     'textarea',
        label:    'Recommendations',
        hint:     'List the key recommendations to address identified privacy risks. Number each recommendation.',
        required: true,
        placeholder: '1. Implement MFA for all users accessing the system.\n2. Update the Privacy Policy to reflect the new data processing activities.\n3. Conduct staff training on handling sensitive information...',
      },
      {
        id:       'senior_officer_name',
        type:     'text',
        label:    'Senior responsible officer name',
        hint:     'The person with senior accountability for privacy outcomes on this project.',
        required: false,
        placeholder: 'e.g. Sam Taylor, Chief Operating Officer',
      },
      {
        id:       'privacy_officer_name',
        type:     'text',
        label:    'Privacy officer name',
        required: false,
        placeholder: 'e.g. Alex Johnson',
      },
      {
        id:       'sign_off_date',
        type:     'date',
        label:    'Date of sign-off',
        required: false,
      },
      {
        id:       'review_date',
        type:     'date',
        label:    'Scheduled date for next review of this PIA',
        hint:     'OAIC guidance recommends PIAs are reviewed when the project changes materially, or at a fixed interval (e.g. annually).',
        required: false,
      },
      {
        id:       'approval_status',
        type:     'select',
        label:    'Approval status',
        required: true,
        options: [
          { value: 'Draft',    label: 'Draft' },
          { value: 'Pending',  label: 'Pending approval' },
          { value: 'Approved', label: 'Approved' },
          { value: 'Rejected', label: 'Rejected — requires revision' },
        ],
      },
      {
        id:       'additional_notes',
        type:     'textarea',
        label:    'Additional notes',
        required: false,
        placeholder: 'Any other relevant information...',
      },
    ],
  },
];
